language: android

addons:
    apt:
        packages:
        - libgd2-xpm
        - ia32-libs
        - ia32-libs-multiarch
        - git
        - libtool
        - automake
        - gradle

android:
    components:
    - platform-tools
    - android-22
    - build-tools-23.0.0
    - extra

jdk: oraclejdk7

notifications:
  email: false

before_install:
    - bash setup.sh
    - source env.sh

install:
    - bash install-package.sh

cache:
    directories:
    - $HOME/ndk/

script:
    - bash build.sh

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file:
    - "$HOME/Telegram-v3.1.3.apk"
  skip_cleanup: true
  on:
    tags: true
env:
    global:
        secure: "TMav7mMoFrobJECwhBW5azFdY74YoZ1ct9KZM0sGZj3HNSumADq4EqCPVRG5Bn3O0k+QM1wdEaiMbKlKjx7nf4OzxOOEIYsRtfWB5fjLpM75LPapy4gDinDJ3Og9a1Km2RmCy3ay7CPXLOcHHMaLiRv9fzoWfd9CoeNMFOoarZPMHjAAIxzAUtjYN3VLMZ2zOx4CXga+SKmyUhxphrHXvLpiZCUHBt5oKP5I2uki7gt0utCNZYhHRUoqxdq+w97B+Zt+kfaBS48ra7/mxZLSFlmSonV7cIiRenG+FUH1L7RrWzncSivrFkhVmyQdjgfqSWJQUcwGZQh8nMwipkkG2xA4NmL2TjtbzZHZrRA2vbNe0JBb7xo0m4DvfaCUBPcl0ZyzQs92SYWiyG+8fIr4LWkFwmGjemdq0Y2hvlTArf0eRVmc7WGHj6RBuW3ooyHnCW6MPpvKQRg2eY75SJdVH/MybHDiXK3ezE9KFBrnIvrrGxYA3CvvM+hVAnERI9e2cwQPpJ7hDXOEJewg0PIoIJYT3bG/3/PZpPPjKM9RPLmKAlgrG7omKZ591iM1Kj2WoHJdW6bQMTFwRS+Zif/Wseoj8j+u5HmgiKOyohRtwccD4AUdeil1b/v+NuHuw7oOr/I2n09bFpeP+CGV8diJPfyCfFhUnzqmi6lw2T3EWYo="
